site_name: Greater Ottawa Mesh Enthusiasts
site_url: https://ottawamesh.ca
repo_name: MeshCore NCR
repo_url: https://github.com/MrAlders0n/MeshCore-NCR  # update this
nav:
  - Home: index.md
  - Community:
      - Getting Involved: community/getting-involved.md
      - Contributing: community/contributing.md
  - Deployment:
      - Coverage: deployment/coverage.md
      - Repeaters: deployment/repeaters.md
      - Repeater Showcase: deployment/repeaters-showcase.md
      - Wanted Repeater Locations: deployment/repeater-wanted-locations.md
      - Frequency Settings: deployment/frequency-settings.md
  - Hardware:
      - Antenna: hardware/recommended-antenna.md
      - Companion Nodes: hardware/recommended-companions.md
      - Repeater Nodes:
          - Overview: hardware/recommended-repeaters.md
          - Repeater Mounting Options: hardware/repeater-mounting-options.md
          - 300mW Solar Repeater Build Guide: hardware/repeater-solar-300mw-diy-build.md
  - MeshCore:
      - General:
          - MeshCore FAQ: meshcore/general-faq.md
          - MeshCore How-To: meshcore/general-howto.md
          - MeshCore Roles: meshcore/general-meshcore-roles.md
      - Configuration:
          - Flashing a Companion: meshcore/flash-companion.md
          - Flashing a Repeater: meshcore/flash-repeater.md
          - Flashing a Room Server: meshcore/flash-room-server.md
          - RAK4631 Custom Display Firmware: meshcore/firmware-rak-custom-display.md
          - Heltec V3 Wi-Fi Firmware: meshcore/firmware-heltec-v3-wifi.md
      - Packet Capture:
          - Packet Capture · Overview: meshcore/packet-capture-overview.md
          - Packet Capture · Companion Listener: meshcore/packet-capture-companion-listener.md
          - Packet Capture · Standalone Repeater Listener: meshcore/packet-capture-standalone-repeater.md
  - Meshtastic:
      - Getting Started: meshtastic/getting-started.md
      - Frequency Settings: meshtastic/frequency-settings.md
  - Resources:
      - Useful Links: resources/useful-links.md

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search
  - macros
  - glightbox:
      touchNavigation: true

theme:
  name: material
  logo: assets/logo-GOME-mkdocs.png
  favicon: assets/favicon-GOME-mkdocs.png
  palette:
    scheme: slate

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

