site_name: Ottawa Mesh
nav:
  - Home: index.md
  - Community:
      - Getting Involved: community/getting-involved.md
  - MeshCore:
      - General:
          - MeshCore FAQ & How-To: meshcore/general-faq-howto.md
          - MeshCore Roles: meshcore/general-meshcore-roles.md
          - MeshCore Frequency Settings: meshcore/general-frequency-settings.md
      - Ottawa Deployment:
          - Repeaters & Coverage: meshcore/repeaters-and-coverage.md
          - Wanted Repeater Locations: meshcore/wanted-repeater-locations.md
      - Recommended Hardware:
          - Antenna: meshcore/recommended-antenna.md
          - Companion Nodes: meshcore/recommended-companions.md
          - Repeater Nodes:
              - Overview: meshcore/recommended-repeaters.md
              - Repeater Mounting Options: meshcore/repeater-mounting-options.md
              - 300mW Solar Repeater Build Guide: meshcore/repeater-solar-300mw-diy-build.md
      - Configuration:
          - Flashing a Companion: meshcore/flash-companion.md
          - Flashing a Repeater: meshcore/flash-repeater.md
          - Flashing a Room Server: meshcore/flash-room-server.md
          - RAK4631 Custom Display Firmware: meshcore/firmware-rak-custom-display.md
          - Heltec V3 Wi-Fi Firmware: meshcore/firmware-heltec-v3-wifi.md
      - Packet Capture:
          - Packet Capture · Overview: meshcore/packet-capture-overview.md
          - Packet Capture · Companion Listener: meshcore/packet-capture-companion-listener.md
          - Packet Capture · Standalone Repeater Listener: meshcore/packet-capture-standalone-repeater.md
  - Meshtastic:
      - Getting Started: meshtastic/getting-started.md
      - Frequency Settings: meshtastic/frequency-settings.md
  - Resources:
      - Useful Links: resources/useful-links.md
theme:
  name: material
  palette:
    scheme: slate      # dark palette
