site_name: Ottawa Mesh
nav:
  - Home: index.md
  - MeshCore:
    - Hardware Overview: meshcore/hardware-overview.md
    - MeshCore FAQ: meshcore/meshcore-faq.md
    - Companion Nodes & Antenna Recommendations: meshcore/companion-nodes-antenna.md
    - RAK-Based Repeaters Note: meshcore/rak-based-repeaters-note.md
    - Repeater Mounting Options: meshcore/repeater-mounting-options.md
    - Flashing a Companion Node: meshcore/flash-companion-node.md
    - Flashing a Repeater Node: meshcore/flash-repeater-node.md
    - Configuring a Room Server: meshcore/configure-room-server.md
    - Build Repeater 路 Solar RAK Unify Box: meshcore/build-repeater-solar-rak-unify-box.md
    - RAK4631 Custom Display Firmware: meshcore/rak-custom-display-firmware.md
    - Heltec V3 Wi-Fi Firmware: meshcore/heltec-v3-wifi-firmware.md
    - Packet Capture 路 Overview: meshcore/packet-capture-overview.md
    - Packet Capture 路 Companion Listener: meshcore/packet-capture-companion-listener.md
    - Packet Capture 路 Standalone Repeater Listener: meshcore/packet-capture-standalone-repeater-listener.md
    - Repeaters & Coverage: meshcore/repeaters-and-coverage.md
    - MeshCore Frequency Settings: meshcore/frequency-settings-meshcore.md
    - Wanted Repeater Locations: meshcore/wanted-repeater-locations.md
  - Meshtastic:
    - Getting Started: meshtastic/getting-started.md
    - Frequency Settings: meshtastic/frequency-settings.md