blank_issues_enabled: false
contact_links:
  - name: Repeaters deployment page
    url: https://ottawamesh.ca/deployment/repeaters/
    about: Read existing repeater deployment information and context.
